### ISSUE TITLE
Old Stencil (from VS) doesn't seem to work on FAVS

### ISSUE THREAD

**Issue by SkySwordMC** [IntellectualSites/FastAsyncVoxelSniper#146]
### Server Implementation

Paper

### Server Version

1.18.1

### Describe the bug

I have old stencils made using Voxel Sniper that doesn't load. However, if i create new one they work as expected.

### To Reproduce

1. place the file in Plugins\FastAsyncVoxelSniper\stencils
2. Type /b stencil fill [Stencil Name]
3. Use gunpowder to place the stencil

[stencils.zip](https://github.com/IntellectualSites/FastAsyncVoxelSniper/files/8011156/stencils.zip)

### Expected behaviour

The stencil should be placed.

### Error log (if applicable)

https://paste.gg/p/anonymous/dd941350c70f4c44a7d4b1f42854b027

### Favs Debugpaste

https://athion.net/ISPaster/paste/view/61c10fcfe0ed49438790aeac5f139ea0

### Favs Version

2.3.0

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

**Comment by NotMyFault** [comment]
@Aurelien30000 Do you know something about stencils or used them before? I can replicate it with the steps provided, however, I never worked with stencils before.

**Comment by Aurelien30000** [comment]
Humm, absolutely no idea, the file format is "incorrect" that's sure. FAVS uses a Bukkit BlockData while older VS versions use direct bytes and ints reading, maybe that makes the difference, see https://github.com/WarCraft/VoxelSniper/blob/spigot-1.15/src/main/java/com/thevoxelbox/voxelsniper/brush/StencilBrush.java#L102

_Using former decoder with bytes reading, no EOF to note._
