### ISSUE TITLE
Restore the VoxelSniper wiki from the web archive

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncVoxelSniper#154]
The official VoxelSniper wiki at https://voxelsniper.fandom.com/wiki/VoxelSniper_Wiki is offline for a few months now.
We would be grateful if someone has an offline copy and looks forward to share it with us to host it again on GitHub pages.

At the moment, the wiki does only exist in the web archive: https://web.archive.org/web/20210711121859/https://voxelsniper.fandom.com/wiki/VoxelSniper_Wiki

**Comment by Recol** [comment]
[VoxelSniper Wiki _ Fandom - MHTML compilation.zip](https://github.com/IntellectualSites/FastAsyncVoxelSniper/files/8310038/VoxelSniper.Wiki._.Fandom.-.MHTML.compilation.zip)
Attached a MHTML of the source page for the VoxelSniper wiki.

**Comment by NotMyFault** [comment]
Thanks so much for your work! I converted the file provided into plain html and deployed it at https://github.com/IntellectualSites/FastasyncVoxelSniper-Documentation/commit/82993c853805c25dd4ed615f446128de4033e626

That will help our contributors a lot to setup a typical wiki-like structure.

**Comment by Recol** [comment]
No worries!
