### ISSUE TITLE
Wiki fpr FAVS

### ISSUE THREAD

**Issue by Leahcimkrob** [IntellectualSites/FastAsyncVoxelSniper#161]
### What feature do you want to see added?

Is there a guide for this? Unfortunately, the wiki no longer exists.

### Are there any alternatives?

No

**Comment by PierreSchwang** [comment]
The migrated wiki can be found at https://intellectualsites.github.io/FastasyncVoxelSniper-Documentation/

**Comment by Leahcimkrob** [comment]
If I click any link, I get Error 404

![image](https://user-images.githubusercontent.com/70509359/167848736-1ada81e9-0b6b-4575-bd02-8fa13d87aa37.png)

**Comment by PierreSchwang** [comment]
Yeah, it's just the one page as of now
You'd have to use Ctrl+F for now, until the wiki is fully migrated

**Comment by Leahcimkrob** [comment]
Is there really only a permission, or where can I find it?

**Comment by PierreSchwang** [comment]
Sorry for the late reply, but based on the source code there is the one mentioned, yes.
Not sure if all brushes have separated permissions tho.

**Comment by Aurelien30000** [comment]
Yes they do, iirc. You can check permissions in this huge file for now: https://github.com/IntellectualSites/FastAsyncVoxelSniper/blob/9140aca06ef2ae1a6cdd72182d1a5cced16654b3/src/main/java/com/thevoxelbox/voxelsniper/BrushRegistrar.java#L86
