### ISSUE TITLE
Splatter Disc Brush Problem

### ISSUE THREAD

**Issue by Honezt** [IntellectualSites/FastAsyncVoxelSniper#163]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

The splatter disc brush does not affect any blocks in heights less that 0,

### To Reproduce

1. do /b sd
2. use any material
3. right-click any block that y is less than 0

### Expected behaviour

splatter disc places blocks on any height

### Favs Debugpaste

https://athion.net/ISPaster/paste/view/c33278a027324a68b1d8f1d287f31eaf

### Favs Version

FastAsyncVoxelSniper version 2.3.1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

**Comment by NotMyFault** [comment]
Update Fawe and Paper, I'm not able to replicate that on up to date versions.


https://user-images.githubusercontent.com/13383509/173227230-12bcefc4-fc5f-4652-acd5-8963a7a83caf.mp4

**Comment by Aurelien30000** [comment]
_Sd and **sdv** are different._
Splatter disc issue is confirmed, actually, only blocks at a height of 0 are considered 😅
