### ISSUE TITLE
Update GAV

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncVoxelSniper#166]
As discussed internally, we want to move all deployed projects under the `com.intellectualsites.<project>` namespace.

TODO
- [x] Prepare repository: https://github.com/IntellectualSites/FastAsyncVoxelSniper/pull/165
- [x] Turn off synchronization of `com.fastasyncvoxelsniper` of the central repository.
- [x] Request the creation of a new staging & release database: https://issues.sonatype.org/browse/OSSRH-81681
  - [x] Grant core team members release permissions, add @Aurelien30000 if desired.
- [x] Draft a new release to turn on sync with the OSSRH.

**Comment by Aurelien30000** [comment]
> Grant core team members release permissions, add @Aurelien30000 if desired.

_I personally prefer to avoid and always have your approbation to trigger a release ;)_

**Comment by NotMyFault** [comment]
> I personally prefer to avoid and always have your approbation to trigger a release ;)

Understandable, though nobody of us does that either, releases are staged and delivered by GH actions: https://github.com/IntellectualSites/FastAsyncVoxelSniper/blob/main/.github/workflows/build.yml#L34
However, pushing a release on GitHub is different to explicit release permissions.

The latter allows you to access the snapshot and release database on https://s01.oss.sonatype.org/ to manage snapshots or close release databases, or you would want general management permissions for this project there.
