### ISSUE TITLE
Fill Down Brush Problem 

### ISSUE THREAD

**Issue by Honezt** [IntellectualSites/FastAsyncVoxelSniper#168]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

Similar to the splatter disc issue before, the fill-down command does not fill below the height of 0.

### To Reproduce

1. /b fd
2. use any material
3. right-click on any heights above zero

### Expected behaviour

it should fill blocks down with the desired material until it intersects another block

### Favs Debugpaste

https://athion.net/ISPaster/paste/view/757d4e1791e4407fbaf2a5d12023ffc7

### Favs Version

FastAsyncVoxelSniper version 2.3.2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

**Comment by Aurelien30000** [comment]
Good catch! Thanks
