### ISSUE TITLE
Installing the plugin

### ISSUE THREAD

**Issue by SouriCats** [IntellectualSites/FastAsyncVoxelSniper#183]
### Server Implementation

Spigot

### Server Version

1.19

### Describe the bug

When lauching the plugin, i always have an error (picture)
![Screenshot_35](https://user-images.githubusercontent.com/110637689/182955786-666ab210-13f6-47b6-85aa-abcbba221ee2.png)

### To Reproduce

I'm on Windows10 / Spigot 1.19 / Java 17 / FastAsyncWorldEdit-Bukkit-2.4.2.jar / fastasyncvoxelsniper-2.6.0.jar

Your work look awesome but we can't use it.

Your's,
SouriCat

### Expected behaviour

launch the plugin without error

### Favs Debugpaste

fastasyncvoxelsniper-2.6.0.jar

### Favs Version

fastasyncvoxelsniper-2.6.0.jar

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

**Comment by PierreSchwang** [comment]
You need to install FastAsyncWorldEdit instead of WorldEdit

**Comment by SouriCats** [comment]
Understood ! 
Thx you're awesome <3
