### ISSUE TITLE
Brushes don't work

### ISSUE THREAD

**Issue by TheKalien** [IntellectualSites/fastasyncvoxelsniper#19]
**[REQUIRED] FastAsyncVoxelSniper Configuration Files**
(my bad for the last post, when I pressed submit new issue there was no template in the text box)
Here is a debug paste  -  https://athion.net/ISPaster/paste/view/b6c982159c8d43d59ceccbba64806f73
Seemingly there is no more information  Voxel other than a  small config containing 4 lines

This is everything that was inside the config in the Voxel folder:
undo-cache-size: 20
message-on-login-enabled: true
litesniper-max-brush-size: 10
litesniper-restricted-materials:

**Required Information**
- FAVS Version Number (`/version VoxelSniper`): 1.0.3-backward
- Spigot/Paper Version Number (`/version`): Spigot_Latest_1.16.4.jar
- Minecraft Version: 1.16.4

**Describe the bug**
There could possibly be more that doesn't work, but when I do /b over or /b bb the commands seem to work in chat but nothing happens when I try to actually use the brushes.

And this is a picture of the commands supposedly working in chat
![image](https://user-images.githubusercontent.com/49004198/112700631-dd0c4080-8e8e-11eb-8676-aebc4954ebcf.png)

I felt it smart to record a short video of the brushes not actually working so here:
https://www.youtube.com/watch?v=ZdhuNF96ovI

**To Reproduce**
Steps to reproduce the behavior: I don't know how this would be reproduced
1. Run  to '...' Not sure how this could be tested

**Plugins being used on the server**
Plugins (3): Vault, VoxelSniper, FastAsyncWorldEdit (WorldEdit)

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/voxel-sniper-flattened/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncVoxelSniper for 1.16.4](https://ci.athion.net/job/FastAsyncVoxelSniper-flattening/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by NotMyFault** [comment]
Superseded by #21
