### ISSUE TITLE
i know this is not a bug report but i want to unbind a brush like the comand none in world edit

### ISSUE THREAD

**Issue by jackowacko14** [IntellectualSites/FastAsyncVoxelSniper#216]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

im playing on a servver and i want to reset the brush like the comand none and i dont know how to do 

### To Reproduce

w

### Expected behaviour

w

### Screenshots / Videos

w14

### Error log (if applicable)

13131

### Favs Debugpaste

/vs debugpaste

### Favs Version

1.18

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

### Anything else?

qeqeqeq

**Comment by NotMyFault** [comment]
Please use our community discord for support: https://discord.gg/intellectualsites
