### ISSUE TITLE
updateCheck error references wrong URL

### ISSUE THREAD

**Issue by SlashQuit** [IntellectualSites/FastAsyncVoxelSniper#271]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Upon failing to connect for an update, the error message says;
"Unable to connect to dev.bukkit.org to check for updates. Improper firewall configuration?"

Firewall configuration allows dev.bukkit.org, and DNS traffic shows that a different DNS record is being queried when this error occurs;
A? update.plugin.party. (37)
A? api.curseforge.com. (36)

Reviewing source code file: VoxelSniperPlugin.java
At the section for:  private double updateCheck(double currentVersion)

The URL is defined here;
URL url = new URL("https://api.curseforge.com/servermods/files?projectids=454430");

But the error says the attempt was to dev.bukkit.org ...
LOGGER.error("Unable to connect to dev.bukkit.org to check for updates. Improper firewall configuration?");

### To Reproduce

Install on a system with a firewall.
Allow dev.bukkit.org by name/IPs.
Wait for plugin to perform a version check.
Error message similar to the following should appear;
[12:02:11 ERROR]: [com.thevoxelbox.voxelsniper.VoxelSniperPlugin] Unable to connect to dev.bukkit.org to check for updates. Improper firewall configuration?

### Expected behaviour

Expected behavior is that the error message should mention the correct URL that it failed to reach.

### Favs Debugpaste

https://athion.net/ISPaster/paste/view/a753ed63a50d49a8980d11a0567d2c32

### Favs Version

FastAsyncVoxelSniper version 2.9.1

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

**Comment by NotMyFault** [comment]
Good catch! Do you want to file a PR addressing the typo?

**Comment by SlashQuit** [comment]
I do not, at this time.
It's been a while since I created a PR on here so it would take a bit to review how to do that.
Just wanted to quickly locate where this error was coming from and submit it before I head out of town.
