### ISSUE TITLE
Exception happing due to size

### ISSUE THREAD

**Issue by OneLiteFeather** [IntellectualSites/FastAsyncVoxelSniper#288]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

Well if a player is acting weirdly enough to input the following commands, it might break on some brushes.

### To Reproduce

I did this:
```
[21:28:48] [Server thread/INFO]: Seelenretterin issued server command: /b 999999999
[21:29:13] [Server thread/INFO]: Seelenretterin issued server command: /b b
[21:29:20] [Server thread/INFO]: Seelenretterin issued server command: /b b on
[21:29:27] [Server thread/INFO]: Seelenretterin issued server command: /b bb
```

### Expected behaviour

No errors and maybe no execution because the brush size is too high

### Error log (if applicable)

https://paste.gg/p/anonymous/764255d03753430c9f95d63509316121

### Favs Debugpaste

 https://athion.net/ISPaster/paste/view/53e59984558b491fae93770cce3c8711

### Favs Version

2.9.4 (from the Cloud Migration PR)

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

**Comment by Aurelien30000** [comment]
Oh! You're not supposed to use such brush sizes :sweat_smile:. Iirc this brush tries to compute the associated volume from the brush radius.

**Comment by TheMeinerLP** [comment]
But good to know now to prevent errors like this 😄
