### ISSUE TITLE
`//goto` without arguments throws `java.lang.ArrayIndexOutOfBoundsException`

### ISSUE THREAD

**Issue by thomasmny** [IntellectualSites/FastAsyncVoxelSniper#294]
### Server Implementation

Paper

### Server Version

1.20

### Describe the bug

When running the `//goto` command without providing any arguments, a `java.lang.ArrayIndexOutOfBoundsException` is thrown

### To Reproduce

1. Perform`//goto` command without any additional arguments

### Expected behaviour

The correct error message is to be sent to the player

### Error log (if applicable)

https://hastebin.com/share/dalibapoku.ruby

### Favs Debugpaste

https://athion.net/ISPaster/paste/view/08afc60f5cca48f9b064356393c0d155

### Favs Version

FastAsyncVoxelSniper version 2.9.3

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

### Anything else?

In the [GotoExecutor](https://github.com/IntellectualSites/fastasyncvoxelsniper/blob/69370d854576a73cb4c5f2618ebb5e26dc7a8e45/src/main/java/com/thevoxelbox/voxelsniper/command/executor/GotoExecutor.java#L36) the `java.lang.ArrayIndexOutOfBoundsException` is caught.
However using
```java 
x = Integer.parseInt(arguments[0]);
z = Integer.parseInt(arguments[1]);
``` 
for getting the x- and z-coordinate input throws the new exception

**Comment by Aurelien30000** [comment]
Hey, thanks for your report! This issue has been fixed in the cloud command system migration (#279).
