### ISSUE TITLE
Updater issue checkbox to include a "favs debugpaste"

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncVoxelSniper#298]
At the bottom of the issue template, the checkbox is supposed to check for a "Favs debugpaste" and not a "Fawe debugpaste", to match the input above: https://github.com/IntellectualSites/fastasyncvoxelsniper/blob/63a1d7ca3bb0b5d073a72a6801b76b35dc814058/.github/ISSUE_TEMPLATE/bug_report.yml?plain=1#L98

**Comment by Dream-IIITN** [comment]
i want to work on this issue

**Comment by OneLiteFeather** [comment]
That is great!
