### ISSUE TITLE
Update wiki URL

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncVoxelSniper#299]
Many places point to the old and inaccessible wiki in this repository:  `https://voxelsniper.fandom.com/wiki/VoxelSniper_Wiki`.

Rather, the old URL should be updated with `https://intellectualsites.gitbook.io/fastasyncvoxelsniper/` in all places: https://github.com/search?q=repo%3AIntellectualSites%2Ffastasyncvoxelsniper+https%3A%2F%2Fvoxelsniper.fandom.com%2Fwiki%2FVoxelSniper_Wiki&type=code

**Comment by 0xsoydev** [comment]
Hello, please assign this issue to me, I am a newbie and this seems pretty easy, let me give it a try

**Comment by 0xsoydev** [comment]
Would still like to give it a try in case it's open

**Comment by NotMyFault** [comment]
> Would still like to give it a try in case it's open

For sure :)

**Comment by 0xsoydev** [comment]
@NotMyFault Need to replace the old link with the new link, wherever I find the old one right?

**Comment by NotMyFault** [comment]
Yes

**Comment by 0xsoydev** [comment]
@NotMyFault Hey I think I have made the required changes, please inform me regarding any mistakes I might have done
