### ISSUE TITLE
Reporting bugs

### ISSUE THREAD

**Issue by TheCalypso** [IntellectualSites/fastasyncvoxelsniper#3]
Hello,

I create this issue to bring you back some bugs. FAWE version used: 1.15-172. FAVS version used: 1.0.3 dated March 31, 2020. Paper version used: Paper-201 1.15.2.

As soon as I start the server I have this warning: 
[03:05:04] [Server thread / WARN]: [VoxelSniper] Loaded class com.sk89q.worldedit.extension.platform.Actor from WorldEdit v1.15-172; 330fc39 which is not a depend, softdepend or loadbefore of this plugin.

Also when I use FAVS with the /b e lift or /b e smooth commands it works for a few clicks and then nothing. I have no error in the console nor a warning in the chat.

Congratulations for the work done on the plugin and then some versions!

TheCalypso

**Comment by NotMyFault** [comment]
The warning can be ignored.
