### ISSUE TITLE
FAWE and FAVS both running separate actions when right clicking with an arrow

### ISSUE THREAD

**Issue by SecretlyJealous** [IntellectualSites/fastasyncvoxelsniper#30]
**[REQUIRED] FastAsyncVoxelSniper Configuration Files**
https://athion.net/ISPaster/paste/view/f4a38642ffe24b2f993c23e940ecdb39

**Required Information**
- FAVS Version Number (`/version VoxelSniper`): VoxelSniper version 1.0.4-backward
- Spigot/Paper Version Number (`/version`): git-Tuinity-"1382473" (MC: 1.16.5)
- Minecraft Version: [1.16.5]

**Describe the bug**
When using `/brush inspect` with an arrow and then **right clicking** a block VoxelSniper will remove the block:
![2021-05-14_14 53 01](https://user-images.githubusercontent.com/10485646/118280816-74bc0180-b4c4-11eb-91b0-11a53d4da2c6.png)

I'm sure this affects other brushes too but it is most noticeable with brushes that are not supposed to change blocks, FAWE and VoxelSniper are both running separate actions with the same tool. Would it be possible to make it so that an item can only be assigned an FAWE function or a VoxelSniper function. Binding `/brush inspect` to an arrow for example should prevent VoxelSniper operations from going through, unbinding the brush with `/brush none` should then allow VoxelSniper operations to be used again. As of right now players need to use `/btool remove` on an arrow before using FAWE brushes every time the server restarts to avoid both plugins from running separate actions.

**To Reproduce**
1. Get an arrow and use /brush inspect
2. **Right click** with the arrow on the ground

**Plugins being used on the server**
BungeeGuard, FastAsyncWorldEdit (WorldEdit), LuckPerms, PlotSquared, spark, VoxelSniper

**Checklist**:

- [X] I included all information required in the sections above
- [X] I made sure there are no duplicates of this report [(Use Search)](https://github.com/IntellectualSites/voxel-sniper-flattened/issues?q=is%3Aissue)
- [X] I made sure I am using an up-to-date version of [FastAsyncVoxelSniper for 1.16.4](https://ci.athion.net/job/FastAsyncVoxelSniper-flattening/)
- [X] I made sure the bug/error is not caused by any other plugin

**Comment by NotMyFault** [comment]
Same scenario like any other plugin binding a tool to an item and another one doing something. Adding a check for Fawe tooling here inevitable opens the door to open more checks in the future of other plugins which is unwanted.
Simply use a different tool but an arrow or gunpowder for inspection, Minecraft has more than enough items for that.
