### ISSUE TITLE
Performer Issue on Snapshot-3.0.0

### ISSUE THREAD

**Issue by DogTag93** [IntellectualSites/FastAsyncVoxelSniper#317]
### Server Implementation

Paper

### Server Version

1.18.2

### Describe the bug

While trying to use FAVS I am unable to use performers. 

On 2.9.4 using the "/performer mm" works properly.

However on Snapshop-3.0.0 they return: 

(Fav) An unexpected error occurred.

I've tried a couple different variations such as mm or mat-mat to be sure. (Please add "/performer" command to the wiki)

### To Reproduce

Try to use the performer command. 

/b b

/b 10

/performer mm

### Expected behaviour

I expect that after I used the "/performer mm" command that I was going to select dirt as my replaceVoxel and air as my Voxel. 

### Error log (if applicable)

https://paste.gg/p/anonymous/aedfba6671c54722b88314065f19f5ac

### Favs Debugpaste

https://athion.net/ISPaster/paste/view/8f74e29b754f4721bec91553328a42e5

### Favs Version

Snapshot 3.0.0

### Checklist

- [X] I have included a debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

### Anything else?

Thanks for creating and maintain one of my most favorite plugins. C:

**Comment by OneLiteFeather** [comment]
Hey @DogTag93 can you update fawe to latest? It is a dependency for favs, so we can exclude that as a factor.

**Comment by Aurelien30000** [comment]
Thanks for reporting the issue! A fixed ``.jar`` archive should be available at: https://github.com/IntellectualSites/fastasyncvoxelsniper/actions/runs/6565807767
Please try it ;)

**Comment by OneLiteFeather** [comment]
I'll try that tomorrow (today in my timezone)

**Comment by OneLiteFeather** [comment]
![grafik](https://github.com/IntellectualSites/fastasyncvoxelsniper/assets/77929075/9692ce29-0b6e-4a56-aea8-64b58502e631)
@DogTag93 you wanted to do it like that, isn't it? Looks like your bug is fixed with the version above from Aurelien.

**Comment by DogTag93** [comment]
I've tested out the FAVS build with the updated FAWE plugin and it appears to be working just fine now. Thank you @OneLiteFeather and @Aurelien30000 for responding. Big Thank!
