### ISSUE TITLE
Release 3.1.0 was not successful

### ISSUE THREAD

**Issue by NotMyFault** [IntellectualSites/FastAsyncVoxelSniper#340]
ref https://github.com/IntellectualSites/fastasyncvoxelsniper/actions/runs/7302208902/job/19900413862

The upload to modrinth was successful, but not to hangar:

<img width="1263" alt="Screenshot 2023-12-22 at 22 26 33" src="https://github.com/IntellectualSites/fastasyncvoxelsniper/assets/13383509/3932769f-0519-4844-b430-955db08a8019">

The upload to CurseForge failed too:
<img width="1090" alt="Screenshot 2023-12-22 at 22 26 58" src="https://github.com/IntellectualSites/fastasyncvoxelsniper/assets/13383509/5ccc778d-5c0d-40e0-9e33-115b5189a5c9">

**Comment by PierreSchwang** [comment]
As newer releases worked fine, I guess that was just a temporary issue with the CF api
