### ISSUE TITLE
`java.lang.NoClassDefFoundError` with FAWE b823

### ISSUE THREAD

**Issue by thomasmny** [IntellectualSites/FastAsyncVoxelSniper#366]
### Server Implementation

Paper

### Server Version

1.20.4

### Describe the bug

In https://github.com/IntellectualSites/FastAsyncWorldEdit/commit/ad5739e014e26dd0f6308ce270762783107eec88 FAWE switched from using Adventure NBT to LinBus. Due to this, FAVS no longer loads

### To Reproduce

1. Start a server with FAWE b823 (or whatever exact build corresponds to the commit above)
2. FAVS doesn't load

### Expected behaviour

Plugin should start

### Error log (if applicable)

https://paste.gg/p/anonymous/c35afc90be9d421dae7b4c32a1652401

### Favs Debugpaste

Can't run command since plugin doesn't load

### Favs Version

FastAsyncVoxelSniper v3.1.1

### Checklist

- [ ] I have included a debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

**Comment by NonSwag** [comment]
can confirm (paper 1.20.6)
