### ISSUE TITLE
plugin doesnt load on 1.21.3

### ISSUE THREAD

**Issue by DaJokni** [IntellectualSites/FastAsyncVoxelSniper#391]
### Server Implementation

Paper

### Server Version

1.21.3

### Describe the bug

trying to run the plugin on a 1.21.3 paper server. server doesn't start up and crashes when the plugin is installed.

### To Reproduce

1. install plugin on a 1.21.3 server
2. start up the server
3. observe how that doesn't happen

### Expected behaviour

server works and plugin works

### Error log (if applicable)

https://mclo.gs/6tUWZKF

### Favs Debugpaste

server does not start up with the plugin on the server

### Favs Version

3.2.1

### Checklist

- [X] I have included a debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

**Comment by Galithin** [comment]
Hey we got any updates on this?

**Comment by ILikeOrangeJuice** [comment]
Hey, will there be a download soon for the version with the above approved bugfix?

**Comment by PierreSchwang** [comment]
> Hey, will there be a download soon for the version with the above approved bugfix?

I'd try and see if FAVS works with 1.21.4 as well and create a new release after

**Comment by DaJokni** [comment]
> > Hey, will there be a download soon for the version with the above approved bugfix?
> 
> I'd try and see if FAVS works with 1.21.4 as well and create a new release after

been using it in 1.21.4 for a while and seems to be working good
