### ISSUE TITLE
Unable to change voxel tools when holding other things in your hand -- Current toolkit not found

### ISSUE THREAD

**Issue by mibby** [IntellectualSites/fastasyncvoxelsniper#4]
Paper dev 273 (Spigot 1.15.2)
FAWE dev 217
FAVS dev 14

FAWE Config
https://paste.ubuntu.com/p/5w2yRsq7S6/
VoxelSniper Config
https://paste.ubuntu.com/p/k8b9qB2cc5/

You can't change voxel brush type when you are holding anything in your hand _other_ than air or arrow/gravel. For example if you are holding dirt and type ``/b s``, it outputs ``Current toolkit not found.``.

**Comment by Aurelien30000** [comment]
That's probably expected, since you bind a brush to a tool actually.
