### ISSUE TITLE
Add tab complete to brush params

### ISSUE THREAD

**Issue by Aurelien30000** [IntellectualSites/fastasyncvoxelsniper#49]
**Is your feature request related to a problem? Please describe.**
Manually writing complex biome/item names is boring, a tab completion system would help users with basic operations.

**Describe the solution you'd like**
Add a tab completion handler to some brush params.

**Describe alternatives you've considered**
Add a method to brush interface to handle completion params, like commands.
Should simply return an empty list by default.

**Additional context**
Can be assigned to me, thanks ;)

**Comment by NotMyFault** [comment]
Not using (modern) command frameworks are the source of all evil.

**Comment by Aurelien30000** [comment]
Right 😅 _but atm I won't dig into such frameworks I have never used_
