### ISSUE TITLE
Commands are not working

### ISSUE THREAD

**Issue by ShockCharge** [IntellectualSites/FastAsyncVoxelSniper#69]
git-Purpur-1171
FastAsyncVoxelSniper 2.2.2
Luckperms 5.3.67 

Tried everything and its still not working. 
I did a verbose on Luckperms and it showed this permissions which is exactly the same shown in the permission lists in the wiki.
![image](https://user-images.githubusercontent.com/48907444/133439613-edf28164-3425-4096-999c-2832e9e658b0.png)

Now I pasted it on my Builder group and its still not working 
![image](https://user-images.githubusercontent.com/48907444/133439726-dcc1a04d-2c03-413e-b46c-74a0729fb2e1.png)
![image](https://user-images.githubusercontent.com/48907444/133439751-cae64219-fc0e-44f6-8790-8a570330fe57.png)
and more.

Please help me out
ShockCharge.

**Comment by NotMyFault** [comment]
And now you raise a new issue without deleting the template you actually will follow.
