### ISSUE TITLE
Permissions not working

### ISSUE THREAD

**Issue by ShockCharge** [IntellectualSites/FastAsyncVoxelSniper#70]
### Server Implementation

Tuinity

### Server Version

1.16.5

### Describe the bug

Before everything:
![image](https://user-images.githubusercontent.com/48907444/133828855-8cf2bfc8-a013-48bc-8249-e7babfbc7f05.png)
![image](https://user-images.githubusercontent.com/48907444/133828889-31f6924a-0fb1-466c-a56c-74d8a054f1a9.png)
![image](https://user-images.githubusercontent.com/48907444/133828908-f74b7053-6387-497a-8cf7-9d5b81341fa2.png)

Followed everything on this wiki provided on your GitHub page.
https://voxelsniper.fandom.com/wiki/VoxelSniper_Wiki

I pasted it on my Builders group in Luckperms and tried every possible permission and it still did not work for them.
![image](https://user-images.githubusercontent.com/48907444/133828614-79ee6874-d29e-484c-a777-6eff98d3410d.png)
![image](https://user-images.githubusercontent.com/48907444/133828639-882531ef-f81a-4ccc-a0ed-d95aa821ff2d.png)
![image](https://user-images.githubusercontent.com/48907444/133828656-fb9d818e-4983-491a-b7b1-e9635005d868.png)
![image](https://user-images.githubusercontent.com/48907444/133828674-64b4b972-b8c5-4f2a-8e70-b40bf094dd4f.png)
![image](https://user-images.githubusercontent.com/48907444/133828684-89cf016d-345d-4e5c-aaab-457894bec8f6.png)

I did a Luckperms verbose (Im Opped Btw) and it showed the exact same thing.
![image](https://user-images.githubusercontent.com/48907444/133828770-a3580cb7-16e1-477d-81e6-cfebbc2a69e4.png)

Am I missing something? please help me out/

### To Reproduce

*

### Expected behaviour

*

### Screenshots / Videos

*

### Error log (if applicable)

*

### Fawe Debugpaste

*

### Favs Version

FastAsyncVoxelSniper 2.2.2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

### Anything else?

None

**Comment by NotMyFault** [comment]
> Am I missing something? please help me out/

Yes, you forgot to read what each field requests and solely left it blank.
