### ISSUE TITLE
Placing Ball Sends a Message Every Time

### ISSUE THREAD

**Issue by JediM4ster** [IntellectualSites/FastAsyncVoxelSniper#79]
### Server Implementation

Paper

### Server Version

1.17.1

### Describe the bug

Any time I place a ball of material it says "No free spot ahead of you found" except I am placing blocks and I am aiming at an area.

### To Reproduce

1. Set material
2. Get the arrow
3. Set brush to ball
4. Place blocks

### Expected behaviour

Remove message unless it's needed

### Screenshots / Videos

https://user-images.githubusercontent.com/72643339/135025746-9c31d8c1-4553-4fac-aa7d-d8684bed9e86.mp4

### Favs Debugpaste

[Server] INFO _The_Jedi_ issued server command: /vs debugpaste
[Server] INFO _The_Jedi_ issued server command: /vs debugpaste
[Server] ran command: vs debugpaste 28.09 00:57:58 
[Server] ran command: /vs debugpaste 28.09 00:57:58 
[Server] INFO Unknown command. Type "/help" for help.

### Favs Version

FastAsyncVoxelSniper version 2.2.2

### Checklist

- [X] I have included a Fawe debugpaste.
- [X] I am using the newest build from https://dev.bukkit.org/projects/favs and the issue still persists.

**Comment by NotMyFault** [comment]
You bound the navigation wand to the arrow. Use `/Tool none` and/or change the defaults.
